site_name: solutions_repo
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Physics:
      - Mechanics:
          - Problem 1: "1 Physics/1 Mechanics/Problem_1.md"
          - Problem 2: "1 Physics/1 Mechanics/Problem_2.md"

